export const SET_TREE_ROWS = 'SET_TREE_ROWS'
export const UPDATE_ROW = 'UPDATE_ROW'
export const DELETE_ROW = 'DELETE_ROW'
export const SET_FORM_REF = 'SET_FORM_REF'
export const PREPARE_ROW = 'PREPARE_ROW'
export const DISABLE_ROWS = 'DISABLE_ROWS' 